Migrate win_iis_virtualdirectory
ansible-collections/microsoft.iis pull request #10
Opened 2024-12-25 12:06 UTC by Yaish25491

##### SUMMARY
Promote the win_iis_virtualdirectory Module from community.windows to microsoft.iis.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
virtualdirectory.ps1
virtualdirectory_info.ps1
virtualdirectory/aliases
virtualdirectory/defaults/main.yml
virtualdirectory/meta/main.yml
virtualdirectory/tasks/main.yml
virtualdirectory/tasks/tests.yml

##### ADDITIONAL INFORMATION
Promote the win_iis_virtualdirectory:
Creating virtualdirectory (set) module.
Creating virtualdirectory_info (get) module.
Updating Documentation file to ymal format.
Updating tests

2024-12-29 13:46 UTC, Yaish25491 commented
All CI checks passed but:
1. See also  - Blacked out in both yaml files, The CI is not able to recognize modules in community nor modules in IIS and fails.
2. supports_check_mode = $true - The CI requires supports_check_mode to exist in both module and module_info file and it must be set to "true", even if in the info file it's redundant, info file is not making any changes, and I cannot set it to "false"

2024-12-31 10:19 UTC, ronger4 requested changes

2024-12-31 10:19 UTC, ronger4 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +  when: run_test.stdout | trim | bool
Since now the oldest server is 2016 and it does support Get-WindowsFeature, this check can be removed.
```suggestion
```

2024-12-31 10:19 UTC, ronger4 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
Since now the oldest server is 2016 and it does support Get-WindowsFeature, this check can be removed.
```suggestion
```

2024-12-31 10:44 UTC, ronger4 commented
> All CI checks passed but:
> 
> 1. See also  - Blacked out in both yaml files, The CI is not able to recognize modules in community nor modules in IIS and fails.
> 2. supports_check_mode = $true - The CI requires supports_check_mode to exist in both module and module_info file and it must be set to "true", even if in the info file it's redundant, info file is not making any changes, and I cannot set it to "false"

Regarding 1
We can't use microsoft.iis.<module_name> till this module is merged.
This should work for the main module:

```
seealso:
- module: microsoft.iis.virtualdirectory_info
- module: community.windows.win_iis_webapplication
- module: community.windows.win_iis_webapppool
- module: community.windows.win_iis_webbinding
- module: community.windows.win_iis_website
```

and for the info module:

```
seealso:
- module: microsoft.iis.virtualdirectory
- module: community.windows.win_iis_webapplication
- module: community.windows.win_iis_webapppool
- module: community.windows.win_iis_webbinding
- module: community.windows.win_iis_website
```

After we push the other modules we can change to the new reference via microsoft.iis

2024-12-31 12:15 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.FailJson("missing required arguments: physical_path")
added

2024-12-31 12:15 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.FailJson("specified folder must already exist: physical_path")
added

2024-12-31 12:15 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +    $module.FailJson($_.Exception.Message)
added

2025-01-01 15:20 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +        $module.FailJson("Virtual directory not found.")
added

2025-01-01 15:20 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +$ErrorActionPreference = "Stop"
removed

2025-01-01 15:23 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +        Get-WebVirtualDirectory -Site $site -Name $name -Application $application -ErrorAction SilentlyContinue
removed

2025-01-01 15:23 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +        $directory_properties = Get-ItemProperty -LiteralPath $directory_path -ErrorAction SilentlyContinue
removed

2025-01-01 15:35 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
Maybe it should be updated to 2016 instead of 2012?

2025-01-01 15:52 UTC, shahargolshani commented on tests/integration/targets/virtualdirectory/aliases
Currently there is only one target for microsoft.iis 
shippable/windows/group1
Change to see the integration tests result in CI

2025-01-01 16:00 UTC, ronger4 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
in 2012 you couldn't run ansible.windows.win_feature
thats why there was a check to make sure on those servers it won't run the module. now its not relevant anymore as all our servers are 2016 and above, this when is not needed.

2025-01-02 07:45 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
changed

2025-01-09 03:42 UTC, jborean93 commented on plugins/modules/virtualdirectory.ps1
> +    if ($module.CheckMode) {
It looks like you've got some form of check mode support already in place, was this just a leftover from the old module?

2025-01-09 03:42 UTC, jborean93 commented on plugins/modules/virtualdirectory.yaml
> +    virtualdirectory:
We always use the fully qualified module name in examples.

2025-01-09 08:09 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +    virtualdirectory:
The correct way is "microsoft.iis.virtualdirectory"?

2025-01-09 08:15 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +    if ($module.CheckMode) {
No, I added the check mode support. 
maybe this part is redundant if I have support with each function - 
example: 
Set-ItemProperty -LiteralPath $directory_path -Name "PhysicalPath" -Value $physical_path -WhatIf:$check_mode

2025-01-09 20:32 UTC, jborean93 commented on plugins/modules/virtualdirectory.ps1
> +    if ($module.CheckMode) {
It is redundant, it means when running in check mode then the whole module run is skipped and we aren't checking that things like your `Set-ItemProperty` is skipped in check mode in our tests.

2025-01-09 20:32 UTC, jborean93 commented on plugins/modules/virtualdirectory.yaml
> +    virtualdirectory:
Yep, `namespace.name.module:`

2025-01-12 08:16 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +    virtualdirectory:
Examples updated

2025-01-12 08:17 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +    if ($module.CheckMode) {
Removed

2025-01-14 20:17 UTC, jborean93 requested changes

2025-01-14 20:17 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.yaml
> +    - Retrive information on am application's virtual directory in IIS
I think this is somewhat redundant and included in the above statement, there's also a typo` am` -> `an`

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +  block:
The name isn't needed here, seems to be a leftover from the older tests.

```suggestion
- block:
```

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +    when: feature_uninstall.reboot_required | default(False)
While normally for tests we want to clean up everything this can be a slow task and all our tests need it. Best to just keep the feature here so we don't slow things down.

```suggestion
```

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory/tasks/tests.yml
> +- name: Create test virtual directory
We need a test for creating a vs in check mode

```yaml
- name: Create test virtual directory
  virtualdirectory:
    state: present
    site: "{{ test_site_name }}"
    name: "{{ test_vdir_name }}"
    physical_path: "{{ test_physical_path }}"
  register: result
  check_mode: true

- name: Verify test virtual directory
  virtualdirectory_info:
    site: "{{ test_site_name }}"
    name: "{{ test_vdir_name }}"
  register: vdir_info_check

- assert:
    that:
    - result is changed
    - not vdir_info_check.exists
```

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory/tasks/tests.yml
> +    - 'result.changed == false'
We need a test for `state: absent` for check, normal, and idempotent scenarios.

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
We don't need this check anymore, 2016 is the baseline.

2025-01-14 20:17 UTC, jborean93 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +    when: feature_uninstall.reboot_required | default(False)
Best to keep this off to make CI a bit more efficient

```suggestion
```

2025-01-15 07:53 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +        connect_as = @{ required = $false; default = "pass_through"; type = "str"; choices = @("specific_user", "pass_through") }
The required_if is failing the code if the default setting isn't set, any thoughts?

2025-01-15 07:54 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.FailJson("missing required arguments: physical_path", $_ )
removed

2025-01-15 11:17 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            New-WebVirtualDirectory @directory_parameters -Force
I didn't find any indication of output but I added the Out-Null just in case.

2025-01-15 11:19 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +    when: feature_uninstall.reboot_required | default(False)
Removed

2025-01-15 13:27 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory/tasks/tests.yml
> +- name: Create test virtual directory
I added a test in check mode

2025-01-15 15:10 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory/tasks/tests.yml
> +    - 'result.changed == false'
Tests added for all 3 states

2025-01-15 15:14 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +  when: run_test.stdout | trim | bool
Updated

2025-01-15 15:52 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.Result.changed = $true
if statement added to address the issue

2025-01-15 15:53 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.FailJson("specified folder must already exist: physical_path", $_ )
removed

2025-01-16 14:27 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +        connect_as = @{ required = $false; default = "pass_through"; type = "str"; choices = @("specific_user", "pass_through") }
Removed required_if and addressed that instead in code.

2025-01-16 14:30 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.Result.msg = "Virtual directory created."
removed

2025-01-16 14:32 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +                $module.Result.msg = "Physical path updated."
removed

2025-01-16 14:32 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +                    $module.Result.msg = "Username Updated."
removed

2025-01-16 14:32 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +                    $module.Result.msg = "Password Updated."
removed

2025-01-16 14:33 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +                    $module.Result.msg = "Username removed."
removed

2025-01-16 14:33 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +            $module.Result.msg = "Virtual directory removed."
removed

2025-01-16 14:37 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +      default: pass_through
removed

2025-01-16 14:46 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +---
changed

2025-01-16 14:48 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +        - If pass_through, IIS uses the identity of the user or application pool identity to access the physical path.
Applied on all values

2025-01-16 14:49 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +        - Required when connect_as is set to specific_user.
Applied on all values

2025-01-16 14:49 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +        - If specific_user, IIS uses the credentials provided in username and password to access the physical path.
applied

2025-01-19 08:56 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +        - Required when connect_as is set to specific_user.
Done

2025-01-19 09:36 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +    }
updated

2025-01-19 10:17 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +            required = $true
I think I understood your request, Code updated.

2025-01-19 11:18 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +    if ($directory) {
module modified to accommodate multiple results, Tests updated.

2025-01-19 12:53 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +            Application = $application
returned keys updated

2025-01-19 12:55 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +            Password = if ($null -ne $directory_properties.password) { $directory_properties.password } else { "" }
Removed, We will add an opt-in option in case there is a great demand by our users.

2025-01-19 13:44 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yaml
> +    - Retrive information on am application's virtual directory in IIS
done

2025-01-19 13:45 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +  block:
removed

2025-01-19 13:52 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.yaml
> +        - The specified folder must already exist.
Added

2025-01-19 18:38 UTC, jborean93 commented on plugins/modules/virtualdirectory.ps1
> +                    }
It's best to move this logic to the start of the module, after we've created the `$module` object but before we do any work.

2025-01-19 18:38 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.yml
> +    sample: |
Looks like we need to update the return sample now the return values are `snake_case`.

2025-01-20 08:05 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yml
> +    sample: |
snake_case updated and password removed from example.

2025-01-20 08:50 UTC, Yaish25491 commented on plugins/modules/virtualdirectory.ps1
> +                    }
Logic moved to the beginning of the module as suggested.

2025-01-20 08:51 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yml
> +    sample: |
Test output updated to snak_case and return values updated

2025-01-21 07:50 UTC, jborean93 requested changes

2025-01-21 07:50 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.ps1
> +    $module.FailJson("Failed to ensure WebAdministration module is loaded.", $_.Exception.Message, $_ )
We want the exception message to be included in the first arg, the second arg is the ErrorRecord/Exception. Right now this is trying to call an overload that doesn't exist.

```suggestion
    $module.FailJson("Failed to ensure WebAdministration module is loaded: $_", $_)
```

2025-01-21 07:50 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.ps1
> +        name = @{ required = $true; type = "str" }
We try and make sure that the `_info` module can return all objects and not just one. This means `name/site` should not be required.

2025-01-21 07:50 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.yml
> +          UserName:
These all still need updating to the `snake_case` format.

2025-01-21 07:50 UTC, jborean93 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +      path: "{{ test_app_tmp_dir.path }}"
This may not be defined if the test fails before getting to when `test_app_tmp_dir` is registered. In any case if it's derived from `remote_tmp_path` we don't need this as the `setup_remote_tmp_dir` handler will clean it up for us.

2025-01-21 07:50 UTC, jborean93 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +      path: "{{ test_app_tmp_dir.path }}"
Same here, I don't think it's needed.

2025-01-21 08:17 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yml
> +          UserName:
Updated to snake_case

2025-01-21 08:19 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +        name = @{ required = $true; type = "str" }
Removed from specs and documentation

2025-01-21 08:21 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory/tasks/main.yml
> +      path: "{{ test_app_tmp_dir.path }}"
Removed

2025-01-21 08:22 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/main.yml
> +      path: "{{ test_app_tmp_dir.path }}"
removed

2025-01-22 20:43 UTC, jborean93 requested changes

2025-01-22 20:43 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.ps1
> +        $directory_properties = Get-ItemProperty -LiteralPath $directory_path
I think this would have to move into the loop as right now it's going to always be the same path. Maybe `$directory_properties = $directory | Get-ItemProperty` inside the loop would work but that's untested.

2025-01-22 20:43 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.yml
> +  - name: Verify test virtual directory
The names should probably be something a bit more descriptive, like `Get information for virtual directory on a specific site`.

2025-01-22 20:43 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.yml
> +  - name: Verify test virtual directory
Same here

2025-01-22 20:43 UTC, jborean93 commented on tests/integration/targets/virtualdirectory_info/tasks/tests.yml
> +  ansible.windows.win_tempfile:
We should just use `win_file` with a directory inside `remote_tmp_dir`. That way it's automatically cleaned up after the test is done.

2025-01-22 20:43 UTC, jborean93 commented on tests/integration/targets/virtualdirectory_info/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
We should also test the other return values and the `vdir_info.directories` count is 1 here.

2025-01-22 20:43 UTC, jborean93 commented on plugins/modules/virtualdirectory_info.ps1
> +    $directory_path = if ($application) {
I don't think this is needed, it should be calculated inside the loop based on the vd object being enumerated.

2025-01-23 06:51 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yml
> +  - name: Verify test virtual directory
updated

2025-01-23 06:51 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.yml
> +  - name: Verify test virtual directory
Updated

2025-01-23 09:38 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/tests.yml
> +  ansible.windows.win_tempfile:
After investigating, win_file only returns true/false when creating a directory and not a path which I need for the virtualdirectory/virtualdirectory_info module.

I will leave it as it is for now.

2025-01-23 09:55 UTC, Yaish25491 commented on tests/integration/targets/virtualdirectory_info/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
Count test added. 
Regarding other returns, they are still Null at this point of the test.

2025-01-23 11:45 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +    $directory_path = if ($application) {
Updated the code to calculate this inside the loop

2025-01-23 12:07 UTC, Yaish25491 commented on plugins/modules/virtualdirectory_info.ps1
> +        $directory_properties = Get-ItemProperty -LiteralPath $directory_path
It looks like it works, It is hard to know with only one directory 
The output remains the same with this edit.

2025-01-27 19:50 UTC, jborean93 requested changes

2025-01-27 19:50 UTC, jborean93 commented on plugins/modules/virtual_directory_info.ps1
> +                    application = $application
Same here, `$name`, `$site`, and `$application` are module input options and not derived from the `$directory` object you are returning.

This is a problem because if you have multiple entries returned by `Get-WebVirtualDirectory` then you'll just be returning the same info for all these properties.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
You should also be checking the other returned values like `username`, etc.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'result_check_mode.changed == true'
No assertions for `vdir_info_check_mode` retrieved above.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
You are not checking `username` here so the check isn't doing too much.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +- name: Delete virtual directory and use pass through authentication
You should also have a `state: absent` check mode test before this one.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory_info/tasks/tests.yml
> +- name: Create test application temporary directory
You shouldn't need this, `remote_tmp_dir` contains a temp directory, we should be re-using that with `win_file` if we need a custom subdir This way it'll be cleaned up at the end of the test.

2025-01-27 19:50 UTC, jborean93 commented on tests/integration/targets/virtual_directory_info/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
The module returns more values, we should be testing them all here.

2025-01-29 10:11 UTC, Yaish25491 commented on plugins/modules/virtual_directory_info.ps1
> +                $directory_properties = $directory | Get-ItemProperty -LiteralPath $directory_path
I've changed the logic to retrieve the sites and drill down from there

2025-01-29 11:10 UTC, Yaish25491 commented on plugins/modules/virtual_directory_info.yml
> +    virtual_directory_info:
Done

2025-01-29 11:10 UTC, Yaish25491 commented on plugins/modules/virtual_directory_info.yml
> +    virtual_directory_info:
Done

2025-01-29 11:14 UTC, Yaish25491 commented on plugins/modules/virtual_directory_info.ps1
> +                $directory_properties = $directory | Get-ItemProperty -LiteralPath $directory_path
I've changed the logic, the directory path is dynamic.
I added a test - THE Info retrieves all the directories If a specific $site is not requested.

2025-01-29 11:15 UTC, Yaish25491 commented on plugins/modules/virtual_directory_info.ps1
> +                    application = $application
solved

2025-01-29 11:29 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'result_check_mode.changed == true'
fixed

2025-01-29 12:23 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
username should return empty because it's pass_through - verified 
I also added checks for name and site.

2025-01-29 12:25 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'result_check_mode.changed == true'
added

2025-01-30 08:19 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +- name: Delete virtual directory and use pass through authentication
update

2025-01-30 12:07 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory/tasks/tests.yml
> +    - 'vdir_info.directories[0].physical_path == test_physical_path'
The username will not represent the desired stat perfectly.
I added a test for the connect_as

2025-01-30 14:00 UTC, Yaish25491 commented on tests/integration/targets/virtual_directory_info/tasks/tests.yml
> +- name: Create test application temporary directory
changed the directory to be created as a sub-directory to the existing one with ein_file and used it for the application creation.

2025-02-02 18:00 UTC, jborean93 approved these changes

2025-02-02 18:00 UTC, merged