Migrate win_iis_webapplication module to new microsoft.iis repository
ansible-collections/microsoft.iis pull request #9
Opened 2024-12-25 10:28 UTC by ronger4

##### SUMMARY

1) Migrate win_iis_webapplication module to new microsoft.iis repository
2) Upgrade the module to the Ansible.Basic style module.
3) Name of the module changed to web_application
4) Documentation updated
5) info module will added and called web_application_info

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

win_iis_webapplication 
##### ADDITIONAL INFORMATION

```paste below
Work in Progress
```

2025-01-05 16:35 UTC, ronger4 commented
Ready for review,
Currently the failure in CI is due to the fact this module is dependent on website and webapppool modules and they are still not merged. Using community repo won't work as there is no dependency on this repo. 

Another point I would like to address is the fact that  :
Running the following won't fail if name that user gave as input is not existing. It will just return an empty application list.
`$applications = Get-WebApplication -Name $name`

I wonder if I need to make sure there will be a failure or the current functionality is ok.

2025-01-09 03:43 UTC, jborean93 commented on tests/integration/targets/web_application/aliases
> +shippable/windows/group4
I know CI is waiting on `website` to me merged but right now this repo only has 1 test group so this should be `shippable/windows/group1`

2025-01-14 19:13 UTC, jborean93 requested changes

2025-01-14 19:13 UTC, jborean93 commented on plugins/modules/web_application_info.ps1
> +    }
It's never really a good idea in PowerShell to use `+=` on an array. The number of values we are dealing with here won't actually make a difference but it's good to get into the habit of just capturing the output. The only caveat here is we wrap the `foreach` loop in `@()` to ensure it's an array value if there is 0 or 1 elements in the loop.

```suggestion
    $module.Result.applications = @(
        foreach ($application in $applications) {
            @{
                name = $application.path.TrimStart('/')
                site = $application.GetParentElement().Attributes["name"].Value
                application_pool = $application.ApplicationPool
                physical_path = $application.PhysicalPath
                enabled_protocols = $application.EnabledProtocols
            }
        }
    )
```

2025-01-14 19:13 UTC, jborean93 commented on plugins/modules/web_application_info.yml
> +        - Name of the web application.
We should add an extra note here and for `site` explaining what happens if either are unset.

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/main.yml
> +    when: feature_uninstall.reboot_required | default(False)
While normally yes we should clean up everything, to make our tests more efficient we will want to keep this feature. This ensure that each test target doesn't waste time installing the features as a preceeding test will have done so already.

```suggestion
```

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: create test app
We need to add a check mode test here as well

```yaml
- name: create test app - check mode
  web_application:
    state: present
    site: "{{ test_site_name }}"
    name: "{{ test_app_name }}"
    physical_path: "{{ test_physical_path }}"
  check_mode: true
  register: result

- name: Fetch info for test app - check mode
  web_application_info:
    name: "{{ test_app_name }}"
  register: test_info_check

- assert:
    that:
    - result.changed == true
    - not test_info_check.exists

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
Ditto here, we should be adding a check mode test here to ensure a change was detected but not actual change occurred.

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +    - test_info.applications[0].physical_path == test_physical_path
Seems like we may want to retrieve the `username` in `web_application_info` so we can properly test that `connect_as: specific_user` worked or not.

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: create new test application pool
This already exists, not sure what the point of this task is.

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +  failed_when: "'connect_as is specific_user but all of the following are missing: username, password' not in failure.msg"
This is an issue with this particular line but we have no tests for

+ `state: absent` in check, normal, and idempotent tasks

2025-01-14 19:13 UTC, jborean93 commented on tests/integration/targets/web_application_info/tasks/main.yml
> +    when: feature_uninstall.reboot_required | default(False)
Ditto here, we can remove this
```suggestion
```

2025-01-14 19:24 UTC, jborean93 requested changes

2025-01-14 19:24 UTC, jborean93 commented on plugins/modules/web_application.ps1
> +            $module.FailJson("missing required arguments: path")
Technically `path` is an alias and the option is `physical_path

```suggestion
            $module.FailJson("missing required arguments: physical_path")
```

2025-01-15 07:45 UTC, ronger4 commented on plugins/modules/web_application.ps1
> +        if ($application_pool) {
I'm not sure I fully understand.
Regarding the first question, $website.ApplicationPool should always have a value because website is required, and website must have a pool (at least the default one).

Your suggestion is to connect this condition to the condition that set later in code:
```
if ($application_pool) {
            $application_parameters.ApplicationPool = $application_pool
        }
```
By adding else ?

2025-01-15 07:58 UTC, ronger4 commented on plugins/modules/web_application.ps1
> +        connect_as = @{ type = "str"; default = "pass_through"; choices = "specific_user", "pass_through" }
Thanks for bringing that up as I have wonders here about it and I forgot to bring it up.

Basically, in the old code the condition was set like that:
```
$connect_as = Get-AnsibleParam -obj $params -name 'connect_as' -type 'str' -validateset 'specific_user', 'pass_through'
$username = Get-AnsibleParam -obj $params -name "username" -type "str" -failifempty ($connect_as -eq 'specific_user')
$password = Get-AnsibleParam -obj $params -name "password" -type "str" -failifempty ($connect_as -eq 'specific_user')
```
Since we moved to ansible.basic I utilized the new syntax and functionality and did:
```
....
....
connect_as = @{ type = "str"; default = "pass_through"; choices = "specific_user", "pass_through" }
        username = @{ type = "str" }
        password = @{ type = "str"; no_log = $true }
    }
    required_if = @(
        , @("connect_as", "specific_user", @("username", "password"))
    )
```

At the beginning I wanted to keep same functionality as before and I didn't add default to connect_as, what happens though is a failure in ansible side when it tries creating the module object:
`$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)
`
I wonder if this is a bug or something we missed in the concept (Hen had the same issue too)
The failure we get is:
```
TASK [web_application : test app is absent (baseline)] *************************
task path: /home/ronger/.ansible/collections/ansible_collections/microsoft/iis/tests/output/.tmp/integration/web_application-ksd_a6ho-ÅÑŚÌβŁÈ/tests/integration/targets/web_application/tasks/tests.yml:8
Using module file /home/ronger/.ansible/collections/ansible_collections/microsoft/iis/plugins/modules/web_application.ps1
Pipelining is enabled.
<10.46.29.214> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 10.46.29.214
EXEC (via pipeline wrapper)
The full traceback is:
Exception calling "Create" with "2" argument(s): "Object reference not set to an instance of an object."
At line:25 char:1
+ $module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NullReferenceException

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 25
fatal: [windows_server]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"Create\" with \"2\" argument(s): \"Object reference not set to an instance of an object.\""
}

```

2025-01-15 10:16 UTC, ronger4 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: create test app
I will add your suggestion.
I do see in code that in checkmode it will return changed = true in cases that checkmode was selected as-well.
Should I consider return changed false in those cases or it's not an issue/ not expected to return false.

2025-01-15 11:00 UTC, ronger4 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
There is an issue here, would appreciate your advice to how to get forward.
In the original module connect_as was displayed to the user as an info. Currently I don't display it in the info module because I didn't want to make site and name as required (and you need both site and app name to know connect_as is pass_through or specific_user). I wanted to give the user an option to not specify any and that way to fetch all the data.

There is an option to fetch the site with a given app name by iterating over all the sites and all applications for each site and comparing the app name. But things are getting more complicated if there is same app name in 2 different sites.

My general point is whether I should add connect_as as part of the info module and making name and site as requirement (user will be able to fetch the specific app name he likes to get info for) or to leave it be like it is now.
In case it stays as is now I can still do the check of the checkmode by using win_powershell module.

2025-01-15 19:22 UTC, jborean93 commented on plugins/modules/web_application.ps1
> +        if ($application_pool) {
At line 66 `$application_pool` looks like it is always going to be defined. It is either provided as a module option or derived through `$website.ApplicationPool` on 46-48. This means we don't need the if check and can always provide it to `$application_parameters` unless for some reason `$website.ApplicationPool` can ever be `$null`.

2025-01-15 19:24 UTC, jborean93 commented on plugins/modules/web_application.ps1
> +        connect_as = @{ type = "str"; default = "pass_through"; choices = "specific_user", "pass_through" }
Hmm I'll have to try it out. If it is a bug we may need to avoid the `requires_if` check and just manually do it after creating the `$module` object.

2025-01-15 19:30 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
Can you not derive the site from the web application object itself? If not then it begs the question why `site` is needed for the normal module itself.

2025-01-15 20:04 UTC, ronger4 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
Sites can have different applications and there is an option to have application with the same name on 2 different sites.
There are ways to derive for example,
fetching the PSPATH of the app and get site from the path.

But again, app name is not unique and can have the same name.
In the main module it make sense to require site because we would want the user to tell on which site he wants the application to be created and in case there are 2 applications on 2 different sites with same name, when he does abesnt we would like to know which specific app he wants to delete.

2025-01-17 01:03 UTC, jborean93 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
What you are saying makes sense to have `site` be mandatory for a web application but what I'm not clear on is why can't we retrieve the connection username details for a web application in the `_info` module.

2025-01-17 08:32 UTC, ronger4 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
1) You mean retrieve username together with connect_as value right?
2) So, in general I can, but in the info module site is not mandatory. This is due to the fact that currently the option are:
a) User doesn't put site nor application - He gets a list of dicts of all the apps.
b) User put site without app - he gets all the apps under a specific site
c) User puts app without site - he gets specific app name (if there are 2 with same name on diff sites, he will get both)
d) user puts both app and site - he gets the data of specific app (this is for cases in which he has 2 apps with same name and he wants to get a specific one).

To retrieve connect_as or username we use the following command (in this case for username):
Get-ItemProperty -LiteralPath "IIS:\Sites\$($site)\$($name)" -Name 'userName'

We must have site.
In case user doesn't give site as an input (as it is not mandatory), it causes issue to fetch that because as written before,
fetching the site by using app name is not stright forward as 2 apps can have same name of different site.

2025-01-21 14:59 UTC, ronger4 commented on tests/integration/targets/web_application/tasks/tests.yml
> +- name: set test app credentials
I added what you suggested.
The best way to fetch site is
$application.GetParentElement().Attributes["name"].Value
Since I already run in a loop through all apps it's not an issue if same web app name gets us multiple results as it is handled the same.

2025-01-21 15:35 UTC, ronger4 commented
All requests taken care for.
Please don't merge yet,
Need to rebase and fetch the change done by Shahar in order to align with the new utils he added to handle removal better and solves the flaky failures.

2025-01-22 15:21 UTC, ronger4 commented
Hi @jborean93,
PR should be ready for review.
I integrated Shahar's changes with the setup_iis util too.
Thanks.

2025-01-22 20:28 UTC, jborean93 approved these changes
Looking great, thanks for sticking through with my reviews!

2025-01-22 20:28 UTC, merged